# Generated by Django 4.2.1 on 2023-05-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=10),
        ),
    ]
