# Generated by Django 4.2.1 on 2023-05-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10),
        ),
    ]
